# Generated by Django 3.1.5 on 2021-01-29 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20210129_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='checked',
        ),
    ]
