# Generated by Django 3.1.5 on 2021-01-29 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_remove_todoitem_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='owner',
        ),
    ]
